name: Bug Report
description: Report a bug with the MiGO Netatmo integration
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please fill out the form below to help us investigate the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I am using the MiGO app (orange flame icon), NOT MiGO Link or myVAILLANT
          required: true
        - label: I have searched for existing issues with the same problem
          required: true
        - label: I have enabled debug logging and collected relevant logs
          required: false

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: "2024.11.0"
    validations:
      required: true

  - type: input
    id: integration-version
    attributes:
      label: Integration Version
      description: What version of this integration are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs
      description: |
        Please paste relevant logs here. Enable debug logging by adding this to your configuration.yaml:
        ```yaml
        logger:
          default: warning
          logs:
            custom_components.migo_netatmo: debug
        ```
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
