name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update version in manifest.json and pyproject.toml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/migo_netatmo/manifest.json
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml

      - name: Create release archive
        run: |
          cd custom_components
          zip -r ../migo_netatmo.zip migo_netatmo

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.event.release.tag_name }}" ./migo_netatmo.zip
